#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import codecs
import arcpy

plik = open('F:/!!!_BAZA_PRG/LISTA.txt','r')
zb=[]
for i in plik:
    zb.append(i.strip())
mxd = arcpy.mapping.MapDocument("CURRENT")
lyr = arcpy.mapping.ListLayers(mxd, "") 
for d in zb:
	for s in lyr:
		expr = "\"jpt_nazwa_\"=\'"+ d +"\'"
		print expr
		arcpy.SelectLayerByAttribute_management("gminy","ADD_TO_SELECTION",expr)
arcpy.RefreshTOC() # odświerzam table of contest
arcpy.RefreshActiveView() #odświeżam aktywne okno mapy
print('koniec')
