#!/usr/bin/env python
# -*- coding: utf-8 -*-
__author__ = 'kamil.kruk.geo@gmail.com'

import codecs
import xlrd
import xlwt
import os
import Tkinter
import tkFileDialog

root = Tkinter.Tk()
root.withdraw()
#usuwa okienko z widoku, bez jego niszczenia
dirname = tkFileDialog.askdirectory(parent=root, initialdir="/", title='Wybierz folder z excelami')
print dirname
nb = raw_input('wpisz końcówke pliku wyjsciowego: ')
for plik in os.listdir(dirname):
    if plik[-4:]== ".xls":
        destinationout= plik[:-4]+ nb + ".xls"
        workbook = xlrd.open_workbook(plik, encoding_override='windows-1250')
        wb = xlwt.Workbook(encoding='windows-1250') #zapis excel
        sheet_names = workbook.sheet_names()
        dl = len(sheet_names)
        for nr in range(0,dl-1):
            sheet = workbook.sheet_by_name(sheet_names[nr])
            ws = wb.add_sheet("a"+str(nr), cell_overwrite_ok=True) #nowy shet do zapisu
            zlicz = ""
            calosc = ""
            i = 0
            colu = sheet.ncols
            #ilosc kolumn w arkuszu
            wier = sheet.nrows
            print (plik[:-4])
            print ("kolumn w arkuszu %s" %colu)
            print ("wiersz w arkuszu %s" %wier)
            try:
                for x in range(0,wier):
                    spr = sheet.cell_value(x,0)
                    if spr != calosc:
                        calosc = spr
                        ws.write(i, 0, calosc)
                        i=i+1
                        zlicz = sheet.cell_value(x,1)
                    else:
                        zlicz = zlicz+ ','+ sheet.cell_value(x, 1)
                    ws.write(i-1, 1, zlicz)
            finally:
                print "koniec"
            wb.save(destinationout)
